= eXXcellent programming challenge

The project provides simple implementation of the CSV file Reader.
It able to read data about football teams and days weather from the CSV files.
There are functions to search for object with minimal parameter value within CSV data.
Object Model is implemented according to data from CSV.
CSV examples are located in \src\main\resources\de\exxcellent\challenge

=== Requirements

For building and running the application you need:

- [JDK 1.8](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
- [Maven 3](https://maven.apache.org)


=== Clone the repository

```
git clone https://github.com/AlenaTurubarova/exxcellent-challenge.git
```

=== Building and running
The project scaffolds provides a Maven `pom.xml` as starting
point. You should be able to start with any IDE or text editor
you are convenient with.

After installing Maven 3.x you should be able to

Build & test your project::
    `mvn verify`

Then to run the main class _de.exxcellent.challenge.App_::
    `mvn exec:java`

To remove the compilation output::
    `mvn clean`

Or use your IDE functionality::
    to run & debug you program.
